(ns example.utils.vehicle)

(def sample-vehicle-data
  {:count 8,
   :next nil,
   :previous nil,
   :results
   [{:passengers "1",
     :consumables "unknown",
     :name "X-34 landspeeder",
     :crew "1",
     :created "2014-12-10T16:13:52.586000Z",
     :edited "2014-12-22T18:21:15.583700Z",
     :films ["https://swapi.co/api/films/1/"],
     :url "https://swapi.co/api/vehicles/7/",
     :length "3.4",
     :vehicle_class "repulsorcraft",
     :manufacturer "SoroSuub Corporation",
     :max_atmosphering_speed "250",
     :pilots [],
     :cost_in_credits "10550",
     :cargo_capacity "5",
     :model "X-34 landspeeder"}
    {:passengers "0",
     :consumables "none",
     :name "Snowspeeder",
     :crew "2",
     :created "2014-12-15T12:22:12Z",
     :edited "2014-12-22T18:21:15.623033Z",
     :films ["https://swapi.co/api/films/2/"],
     :url "https://swapi.co/api/vehicles/14/",
     :length "4.5",
     :vehicle_class "airspeeder",
     :manufacturer "Incom corporation",
     :max_atmosphering_speed "650",
     :pilots
     ["https://swapi.co/api/people/1/"
      "https://swapi.co/api/people/18/"],
     :cost_in_credits "unknown",
     :cargo_capacity "10",
     :model "t-47 airspeeder"}
    {:passengers "1",
     :consumables "1 day",
     :name "Imperial Speeder Bike",
     :crew "1",
     :created "2014-12-18T11:20:04.625000Z",
     :edited "2014-12-22T18:21:15.920537Z",
     :films ["https://swapi.co/api/films/3/"],
     :url "https://swapi.co/api/vehicles/30/",
     :length "3",
     :vehicle_class "speeder",
     :manufacturer "Aratech Repulsor Company",
     :max_atmosphering_speed "360",
     :pilots
     ["https://swapi.co/api/people/1/"
      "https://swapi.co/api/people/5/"],
     :cost_in_credits "8000",
     :cargo_capacity "4",
     :model "74-Z speeder bike"}
    {:passengers "0",
     :consumables "unknown",
     :name "Sith speeder",
     :crew "1",
     :created "2014-12-20T10:09:56.095000Z",
     :edited "2014-12-22T18:21:16.095041Z",
     :films ["https://swapi.co/api/films/4/"],
     :url "https://swapi.co/api/vehicles/42/",
     :length "1.5",
     :vehicle_class "speeder",
     :manufacturer "Razalon",
     :max_atmosphering_speed "180",
     :pilots ["https://swapi.co/api/people/44/"],
     :cost_in_credits "4000",
     :cargo_capacity "2",
     :model "FC-20 speeder bike"}
    {:passengers "1",
     :consumables "unknown",
     :name "Koro-2 Exodrive airspeeder",
     :crew "1",
     :created "2014-12-20T17:17:33.526000Z",
     :edited "2014-12-22T18:21:16.140018Z",
     :films ["https://swapi.co/api/films/5/"],
     :url "https://swapi.co/api/vehicles/45/",
     :length "6.6",
     :vehicle_class "airspeeder",
     :manufacturer
     "Desler Gizh Outworld Mobility Corporation",
     :max_atmosphering_speed "800",
     :pilots ["https://swapi.co/api/people/70/"],
     :cost_in_credits "unknown",
     :cargo_capacity "80",
     :model "Koro-2 Exodrive airspeeder"}
    {:passengers "1",
     :consumables "unknown",
     :name "XJ-6 airspeeder",
     :crew "1",
     :created "2014-12-20T17:19:19.991000Z",
     :edited "2014-12-22T18:21:16.150194Z",
     :films ["https://swapi.co/api/films/5/"],
     :url "https://swapi.co/api/vehicles/46/",
     :length "6.23",
     :vehicle_class "airspeeder",
     :manufacturer
     "Narglatch AirTech prefabricated kit",
     :max_atmosphering_speed "720",
     :pilots ["https://swapi.co/api/people/11/"],
     :cost_in_credits "unknown",
     :cargo_capacity "unknown",
     :model "XJ-6 airspeeder"}
    {:passengers "0",
     :consumables "unknown",
     :name "Flitknot speeder",
     :crew "1",
     :created "2014-12-20T18:15:20.312000Z",
     :edited "2014-12-22T18:21:16.335005Z",
     :films ["https://swapi.co/api/films/5/"],
     :url "https://swapi.co/api/vehicles/55/",
     :length "2",
     :vehicle_class "speeder",
     :manufacturer
     "Huppla Pasa Tisc Shipwrights Collective",
     :max_atmosphering_speed "634",
     :pilots ["https://swapi.co/api/people/67/"],
     :cost_in_credits "8000",
     :cargo_capacity "unknown",
     :model "Flitknot speeder"}
    {:passengers "unknown",
     :consumables "unknown",
     :name "Emergency Firespeeder",
     :crew "2",
     :created "2014-12-20T19:50:58.559000Z",
     :edited "2014-12-22T18:21:16.450655Z",
     :films ["https://swapi.co/api/films/6/"],
     :url "https://swapi.co/api/vehicles/62/",
     :length "unknown",
     :vehicle_class "fire suppression ship",
     :manufacturer "unknown",
     :max_atmosphering_speed "unknown",
     :pilots [],
     :cost_in_credits "unknown",
     :cargo_capacity "unknown",
     :model "Fire suppression speeder"}]})
